app:
  datasourceh2:
    jdbcUrl: jdbc:h2:~/database/tester
    driverClassname: org.h2.Driver
    username: usr
    password: pwd

  datasourcepg:
    jdbcUrl: jdbc:postgresql://localhost:5432/tester
    driverClassname: org.postgresql.Driver
    username: usr
    password: pwd

server:
  port: 8080
  servlet.context-path: /transData
  error:
    include-message: always
    whitelabel.enabled: false
    path: /error

spring:
  main.banner-mode: off
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
